name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-deploy-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deploy-

      - run: npm install
      - run: npm run build

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          user_name: liuyib
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: update web site (by ci)
          disable_nojekyll: true
