name: sync

on: page_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:liuyib/tdsheepvillage-tools.git
          destination-repo: git@gitee.com:liuyibo0616/tdsheepvillage-tools.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: liuyibo0616
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: liuyibo0616/tdsheepvillage-tools
          branch: gh-pages
